name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Si tu as une étape de build, exécute-la ici
      - name: Build the project
        run: npm run build --if-present

      # Exécuter les tests
      - name: Run tests
        run: npm test
